# Generated by Django 4.2.1 on 2025-04-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_star_photo_alter_star_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='death_date',
            field=models.DateField(blank=True, help_text='Оставьте пустым для живых знаменитостей', null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название страны'),
        ),
    ]
